[package]
name = "carson-mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
futures = "*"
tokio = "*"

[dependencies.mongodb]
version = "2.3.1"
features = ["tokio-sync"]

